' https://gitlab.cta-observatory.org/cta-computing/icds/icd-dpps-ict/-/issues/2
@startuml mmoda-schema
!include <cloudogu/common>
!include <cloudogu/tools/k8s>


footer DevOps diagram for DPPS ICT ICD
scale max 1024 width

skinparam {
    ' linetype polyline
    ' nodesep 15
    ' ranksep 30
    defaultFontSize 19
    arrowFontSize 19
    rectangleRoundCorner 30
    rectangleBorderThickness 0.5
}


' participant "<img:grb.jpg>" as blah

' rectangle "Gitlab.in2p3.fr" as Gitlab.in2p3.fr {

' }

' [Sky Transients] as transients #SkyBlue

' rectangle "JupyterHub" as JupyterHub {

' }



[arXiv] as arXiv #LightYellow

[Astro Alert Stream] as astro_alert_stream #LightYellow

' transients --up--> astro_alert_stream

' rectangle "github" as github {

' }

' rectangle "galaxy" as galaxy {

' }

' rectangle "DACE" as DACE {

' }




' rectangle "RDF documents" as RDF_documents {

' }


rectangle "UNIGE DSIC K8S" as unige_dstic_k8s #WhiteSmoke {
  
  rectangle "MMODA Instance" as mmoda #LightGray {
    [dispatcher] as dispatcher
    [frontend] as frontend
    [INTEGRAL backend] as integral_backend
    [backend] as backend
  }


 [Knowledge Graph (fuseki)] as fuseki

 [NLP Bot] as NLP #LightSalmon
 [ODA Bot\n(controller)] as ODA_Bot #LightSalmon
}



rectangle "SDSC" as SDSC #WhiteSmoke {
  rectangle "gitlab.renkulab.io" as gitlab_renkulab_io #LightGray {
    [tool\nGRB detection] as astro_tool_GRB_detection
    [tool\nEuclid] as astro_tool_Euclid_Phosphoros
    [tool\nGaia] as astro_tool_Gaia
    [tool\nLIGO] as astro_tool_LIGO
    [tool\nMeerKAT] as astro_tool_MeerKAT
  }

  [Renku] as Renku #LightSkyBlue

  [Renku KG] as renku_kg  #GoldenRod
}

[Renku] as Renku #LightSkyBlue

Renku -down-> gitlab_renkulab_io


ODA_Bot <-- gitlab_renkulab_io



[gitlab.astro.unige.ch] as gitlab_astro_unige_ch





NLP <--- astro_alert_stream
NLP <--- arXiv

NLP --up-> fuseki

[GraphSearch] as GraphSearch

NLP ---> GraphSearch

[Wikipedia] as Wikipedia #LightYellow

GraphSearch ---> Wikipedia

' gitlab_runners -down-> mmoda : CI/CD

gitlab_astro_unige_ch ---> dispatcher : CI/CD
gitlab_astro_unige_ch ---> frontend : CI/CD

ODA_Bot ---> backend

rectangle "Ontotogies" as ontotogies #LightGoldenRodYellow {
  [IVOA Ontotogy] as IVOA_Ontotogy #GoldenRod
  [Schema.org] as Schema.org #GoldenRod
  [odahub.io] as odahub_io_ontotogy #GoldenRod
}

' ontotogies ---> ODA_Bot

ontotogies ---> renku_kg 
ontotogies ---> fuseki


fuseki ---> ODA_Bot


[Galaxy] as galaxy 

ODA_Bot ---> galaxy


[Lesta] as lesta
[baobab] as baobab
[yggdrasil] as yggdrasil

integral_backend ---> lesta 
integral_backend ---> baobab 
integral_backend ---> yggdrasil


rectangle "Isilon" as isilon #LightGray {
  [INTEGRAL data] as integral_data
}

' isilon -down-> lesta

actor "Astro Analysis User" as User #LightGreen

User --up--> GraphSearch #DarkGoldenRod : search
User --up--> frontend #DarkGoldenRod : UI_analysis
User --up--> dispatcher #DarkGoldenRod : API analysis
User --up--> galaxy #DarkGoldenRod : UI analysis


' myimage : <img:grb.jpg>

actor "Astro Analysis Developer" as AstroDeveloper #LightSteelBlue

AstroDeveloper --up--> Renku #DarkGoldenRod : tool development
AstroDeveloper --up--> gitlab_renkulab_io #DarkGoldenRod : tool development

actor "ODA Platform Developer" as ODAPlatformDeveloper #LightSteelBlue

ODAPlatformDeveloper --up-> gitlab_astro_unige_ch #DarkGoldenRod  : platform development
ODAPlatformDeveloper --up-> ontotogies #DarkGoldenRod 

@enduml
